This is a Python Notebook to work and understand with numpy arrays.

Numpy  - Numerical Python (Numerical Python (NumPy) supports multidimensional arrays over which you can easily apply mathematical operations)

NumPy is the foundational package for mathematical computing in Python.

In [0]:
import numpy as np # You can perform simple Math calculations to complex Deep Learning tasks on numpy!


In [0]:
distance = [10,15,17,26]
time = [0.3, 0.47, 0.55, 1.20]
# type(distance)

In [0]:
# Converted distance list into numpy array of distance
np_dist = np.array(distance)
np_time = np.array(time)
# type(np_dist) 
# type(np_time)

numpy.ndarray

In [0]:
speed = np_dist/np_time

In [0]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [0]:
# Check

# How many elements will the following code print?

print(np.linspace(4,13,7)) # Prints a total 7 equally spaced values in between 4 & 13 (including)

[ 4.   5.5  7.   8.5 10.  11.5 13. ]


In [0]:
print(np.linspace(4,13,2))

[ 4. 13.]


In [0]:
# Attributes of the ndarray
# ndim

np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])
np_city.ndim

['NYC' 'LA' 'Miami' 'Houston']


In [0]:
np_city_with_state = np.array([['NYC', 'LA', 'Miami', 'Houston'],['NY', 'CA', 'FL', 'TX']])
np_city_with_state.ndim

2

In [0]:
# Numpy’s array class is “ndarray,” also referred to as “numpy.ndarray.” The attributes of ndarray are:

# np_city_with_state.shape # Has 2 rows and 4 columns
np_city.shape # Has 4 rows 1 column

(4,)

In [0]:
# In Class Excercise
#Print a np array with shape (1,4)

#### Your code here####
#### Your code here####
# Clue: np_city=np.array([['NYC','LA','Miami','Houston']])

In [0]:
# Size
print(np_city.size, np_city_with_state.size)

4 8


In [0]:
np_city.dtype

dtype('<U7')

In [0]:
np_city_with_state.dtype

dtype('<U7')

In [0]:
# Accessing Array Elements: Indexing

cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
first_trial = cyclist_trials[0]

In [0]:
first_trial

[10, 15, 17, 26]

In [0]:
second_trail = cyclist_trials[1]

In [0]:
second_trail

array([12, 11, 21, 24])

In [0]:
first_cyclist_firstTrail = cyclist_trials[0][0]

In [0]:
first_cyclist_firstTrail

10

In [0]:
first_cyclist_all_trails = cyclist_trials[:,0]

In [0]:
first_cyclist_all_trails

array([10, 12])

In [0]:
# Slicing your np arrays

cyclist_trials.shape

(2, 4)

In [0]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
two_cyclist_trial_data = cyclist_trials[:,1:3] # The first colon : means, all the rows & 1:3 means from 1st col upto 3rd col

In [0]:
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [0]:
# To get the all rows and second column please fill this ?
two_cyclist_trial_data = cyclist_trials[:,?]



In [0]:
first_col = cyclist_trials[:,0]
first_col

array([10, 12])

In [0]:
third_col = cyclist_trials[:,2]
third_col

array([17, 21])

In [0]:
first_third_col = cyclist_trials[:,(0,2)]
first_third_col

array([[10, 17],
       [12, 21]])

In [0]:
# Iterate over elements in an array
for x in cyclist_trials:
  print(x)

[10 15 17 26]
[12 11 21 24]


In [0]:
for y in first_third_col:
  print(y)

[10 17]
[12 21]


In [0]:
# Indexing with boolean arrays
test_scores = np.array([[83,71,57,63], [54,68, 81, 45]])

In [0]:
passing_score = test_scores>60

In [0]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [0]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

In [0]:
# In class excercise
# https://www.hackerrank.com/challenges/python-loops/problem

In [0]:
# Copy and Views

NYC_Borough = np.array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'])
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [0]:
Boroughs_in_NYC = NYC_Borough


In [0]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [0]:
Boroughs_in_NYC is NYC_Borough # Both objects are same and no new copy is made

True

In [0]:
# Creates a shallow copy or a new object
View_of_Borough_in_NYC = Boroughs_in_NYC.view()

In [0]:
len(View_of_Borough_in_NYC)


5

In [0]:
View_of_Borough_in_NYC is Boroughs_in_NYC

False

In [0]:
View_of_Borough_in_NYC[4] = 'Central Park'

In [0]:
View_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [0]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [0]:
Copy_of_NYC_Borough = NYC_Borough.copy()

In [0]:
Copy_of_NYC_Borough is NYC_Borough

False

In [0]:
# Universal functions
import numpy as np
np_sqrt = np.sqrt([2,4,9,16])
np_sqrt

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([1.41421356, 2.        , 3.        , 4.        ,        nan])

In [0]:
from numpy import pi
np.cos(0)

1.0

In [0]:
np.sin(pi/2)

1.0

In [0]:
np.cos(pi)

-1.0

In [0]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3, -1.4])


array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [0]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [0]:
# Manipulate shapes
# Flatten, Resize, Reshape, Stack, Split

new_cyclist_trials = np.array([[10,15,17,26,13,19], [12,11,21,24,14,33]])

In [0]:
new_cyclist_trials.flatten() #Flattens the data (copy)
# new_cyclist_trials.ravel() #Flattens the data

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 33])

In [0]:
new_cyclist_trials.reshape(2,6) # Ensure number of elements are the same!

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 33]])

In [0]:
np.hsplit(new_cyclist_trials, 2) # Reshape and split horizontally from 2nd column

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 33]])]

In [0]:
new_cyclist_1 = np.array([10,15,17,26,13,19])
new_cyclist_2 = np.array([12,11,21,24,14,23])

In [0]:
np.hstack((new_cyclist_1, new_cyclist_2)) #Stack horizontally

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [0]:
# Checkpoint
# Broadcast

array_a = np.array([2,3,5,8])
array_b = np.array([0.3,0.3,0.3,0.3])

# Multiply arrays
array_a*array_b


array([0.6, 0.9, 1.5, 2.4])

In [0]:
# Create a variable with scalar value
scalar_c = 0.3
# Mutiply 1D array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [0]:
# Broadcast limitations
# Create a new array with a different shape
array_d = np.array([4,3])

In [0]:
array_a*array_d

ValueError: ignored

In [0]:
# A larger example for broadcast

np_week_one = np.array([105,135, 195, 120, 165])
np_week_two = np.array([123,156, 230, 200, 147])

In [0]:
total_earning = np_week_one + np_week_two

total_earning

array([228, 291, 425, 320, 312])

In [0]:
np_week_one_hrs = np_week_one /15

In [0]:
np_week_one_hrs

array([ 7.,  9., 13.,  8., 11.])

In [0]:
# Basics of Linear Algebra
test_scores = np.array([[83,71,70,91,89],[54,67,78,65,92]])

In [0]:
test_scores.transpose()

array([[83, 54],
       [71, 67],
       [70, 78],
       [91, 65],
       [89, 92]])

In [0]:
# Inverse and trace functions
inverse_array = np.array([[10,20],[15,25]])
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [0]:
trace_array = np.array([[10,20],[22,31]])
np.trace(trace_array) # Sum of the diagonal elements

41

In [0]:
# 10 20| -0.5 0.4
# 15 25| 0.3  -0.2

In [0]:

# Step to upload the file
from google.colab import files
uploaded = files.upload()

Saving Olympic 2012 Medal Tally.xlsx to Olympic 2012 Medal Tally.xlsx


In [0]:
!ls
!pwd

 anscombe.json		        mnist_test.csv			 README.md
 california_housing_test.csv    mnist_train_small.csv
 california_housing_train.csv  'Olympic 2012 Medal Tally.xlsx'
/content/sample_data


In [0]:
cd sample_data/


/content/sample_data


In [0]:
!ls


anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [0]:
# Assignment 1

#Import required library
import numpy as np

#Manually add the dataset
np_country = np.array(['Algeria','Angola','Argentina','Australia','Austria',
                       'Bahamas','Bangladesh','Belarus','Belgium','Bhutan',
                       'Brazil','Bulgaria','Cambodia','Cameroon','Chile','China',
                       'Colombia','Cyprus','Denmark','El Salvador','Estonia',
                       'Ethiopia','Fiji','Finland','France','Georgia','Ghana',
                       'Grenada','Guinea','Haiti','Honduras','Hungary','India',
                       'Indonesia','Ireland','Italy','Japan','Kenya',' South Korea',
                       'Liberia','Malaysia','Mexico',' Morocco','Nepal','New Zealand',
                       'Norway','Pakistan',' Peru','Qatar','Russia','Singapore',
                       'South Africa','Spain','Sweden','Switzerland','Thailand',
                       'United Arab Emirates','United Kingdom','United States',
                       'Uruguay','Venezuela','Vietnam','Zimbabwe'])
np_gdp = np.array([2255.225482,629.9553062,11601.63022,25306.82494,27266.40335,
                   19466.99052,588.3691778,2890.345675,24733.62696,1445.760002,
                   4803.398244,2618.876037,590.4521124,665.7982328,7122.938458,
                   2639.54156,3362.4656,15378.16704,30860.12808,2579.115607,
                   6525.541272,229.6769525,2242.689259,27570.4852,23016.84778,
                   1334.646773,402.6953275,6047.200797,394.1156638,385.5793827,
                   1414.072488,5745.981529,837.7464011,1206.991065,27715.52837,
                   18937.24998,39578.07441,478.2194906,16684.21278,279.2204061,
                   5345.213415,6288.25324,1908.304416,274.8728621,14646.42094,
                   40034.85063,672.1547506,3359.517402,36152.66676,3054.727742,
                   33529.83052,3825.093781,15428.32098,33630.24604,39170.41371,
                   2699.123242,21058.43643,28272.40661,37691.02733,9581.05659,
                   5671.912202,757.4009286,347.7456605])


In [0]:
np_country.size, np_gdp.size


(63, 63)

In [0]:
# Find and print the name of the country with the highest GDP,
np_country[np.argmax(np_gdp)]

'Norway'

In [0]:
# Find and print the name of the country with the lowest GDP,
np_country[np.argmin(np_gdp)]


'Ethiopia'

In [0]:
# Print out text and input values iteratively


{'Algeria': 2255.225482, 'Angola': 629.9553062, 'Argentina': 11601.63022, 'Australia': 25306.82494, 'Austria': 27266.40335, 'Bahamas': 19466.99052, 'Bangladesh': 588.3691778, 'Belarus': 2890.345675, 'Belgium': 24733.62696, 'Bhutan': 1445.760002, 'Brazil': 4803.398244, 'Bulgaria': 2618.876037, 'Cambodia': 590.4521124, 'Cameroon': 665.7982328, 'Chile': 7122.938458, 'China': 2639.54156, 'Colombia': 3362.4656, 'Cyprus': 15378.16704, 'Denmark': 30860.12808, 'El Salvador': 2579.115607, 'Estonia': 6525.541272, 'Ethiopia': 229.6769525, 'Fiji': 2242.689259, 'Finland': 27570.4852, 'France': 23016.84778, 'Georgia': 1334.646773, 'Ghana': 402.6953275, 'Grenada': 6047.200797, 'Guinea': 394.1156638, 'Haiti': 385.5793827, 'Honduras': 1414.072488, 'Hungary': 5745.981529, 'India': 837.7464011, 'Indonesia': 1206.991065, 'Ireland': 27715.52837, 'Italy': 18937.24998, 'Japan': 39578.07441, 'Kenya': 478.2194906, ' South Korea': 16684.21278, 'Liberia': 279.2204061, 'Malaysia': 5345.213415, 'Mexico': 6288.2532

In [0]:
# Print out the entire list of the countries with their GDPs, and
print(dict(zip(np_country,np_gdp)))

{'Algeria': 2255.225482, 'Angola': 629.9553062, 'Argentina': 11601.63022, 'Australia': 25306.82494, 'Austria': 27266.40335, 'Bahamas': 19466.99052, 'Bangladesh': 588.3691778, 'Belarus': 2890.345675, 'Belgium': 24733.62696, 'Bhutan': 1445.760002, 'Brazil': 4803.398244, 'Bulgaria': 2618.876037, 'Cambodia': 590.4521124, 'Cameroon': 665.7982328, 'Chile': 7122.938458, 'China': 2639.54156, 'Colombia': 3362.4656, 'Cyprus': 15378.16704, 'Denmark': 30860.12808, 'El Salvador': 2579.115607, 'Estonia': 6525.541272, 'Ethiopia': 229.6769525, 'Fiji': 2242.689259, 'Finland': 27570.4852, 'France': 23016.84778, 'Georgia': 1334.646773, 'Ghana': 402.6953275, 'Grenada': 6047.200797, 'Guinea': 394.1156638, 'Haiti': 385.5793827, 'Honduras': 1414.072488, 'Hungary': 5745.981529, 'India': 837.7464011, 'Indonesia': 1206.991065, 'Ireland': 27715.52837, 'Italy': 18937.24998, 'Japan': 39578.07441, 'Kenya': 478.2194906, ' South Korea': 16684.21278, 'Liberia': 279.2204061, 'Malaysia': 5345.213415, 'Mexico': 6288.2532

In [0]:
# Print the highest GDP value, lowest GDP value, 
# mean GDP value, standardized GDP value, and the sum of all the GDPs.



In [0]:
# Assignment 2
# For the following dataset find out the below answers

# Country	Country Code	Year	Medal Tally
# Gold	Silver	Bronze
# Great Britain	GBR	2012	29	17	19
# China 	CHN	2012	38	28	22
# Russia	RUS	2012	24	25	32
# United States	US	2012	46	28	29
# Korea	KOR	2012	13	8	7
# Japan	JPN	2012	7	14	17
# Germany	GER	2012	11	11	14
import numpy as np
np_olympic_country = np.array(['GBR','CHN',"RUS",'US','KOR','JPN','GER'])
np_gold = np.array([29,38,24,46,13,7,11])
np_silver = np.array([17,28,25,28,8,14,11])
np_bronze = np.array([19,22,32,29,7,17,14])

In [0]:

# Print the index name & country name for maximum number of golds
max_gold_index = np_gold.argmax() # Prints the index with the maximum argument value
max_gold_index

# Print the country name for maximum number of golds
print(np_olympic_country[max_gold_index])

US


In [0]:
# Print countries that have more than >20 golds
print(np_olympic_country[np_gold>20])

['GBR' 'CHN' 'RUS' 'US']


In [0]:
# Print the medal tally
np_tally=np_gold+np_silver+np_bronze
np_olympic_country, np_tally

(array(['GBR', 'CHN', 'RUS', 'US', 'KOR', 'JPN', 'GER'], dtype='<U3'),
 array([ 65,  88,  81, 103,  28,  38,  36]))

In [0]:
# Print each country name with the corresponding number of gold medals
i=0
while i < np_olympic_country.size:
  print (np_olympic_country[i],np_gold[i])
  i=i+1

GBR 29
CHN 38
RUS 24
US 46
KOR 13
JPN 7
GER 11


In [0]:
# Print each country name with the total number of medals won
i=0
while i < np_olympic_country.size:
  print (np_olympic_country[i],np_tally[i])
  i=i+1

GBR 65
CHN 88
RUS 81
US 103
KOR 28
JPN 38
GER 36


In [0]:
# End of Assignment 2 please complete this on your own!

# Please complete Assignment 1 on your own by tomorrow 10 am IST!



In [0]:
# Scipy and the different Sub-packages; Enumerate the list
# Integrals
from scipy.integrate import quad



In [0]:
def integrateFunction(x):
  return x*x

In [0]:
quad(integrateFunction,0,1)

(0.33333333333333337, 3.700743415417189e-15)

In [0]:
def integrateFn(x,a,b):
  return x*a+b

a = 3
b = 2 

In [0]:
quad(integrateFn, 0, 1, args = (a,b))

(3.5, 3.885780586188048e-14)

In [0]:
# Multiple integration
import scipy.integrate as integrate
def f(x,y):
  return x+y
integrate.dblquad(f,0,1,lambda x:0, lambda x:2)

(3.0, 4.436070580899685e-14)

In [0]:
# Linear Algebra

import numpy as np
from scipy import linalg
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [0]:
type(matrix)

numpy.ndarray

In [0]:
linalg.inv(matrix) #Inverse of a matrix

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [0]:
linalg.det(matrix) #Determinant of a matrix

58.0

In [0]:
import numpy as np
from scipy import linalg

numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])
numArrValue = np.array([21,9,6])

In [0]:
linalg.solve(numArray, numArrValue)

array([ 4.95,  4.35, -1.95])

In [0]:
numArray1 = np.array([[2,3],[-1,5]])
numArrValue1 = np.array([21,9])
linalg.solve(numArray1, numArrValue1)

array([6., 3.])

In [0]:
# Singular Value Decompisition (SVD)
numSvdArr = np.array([[3,5,1],[9,5,7]])
numSvdArr.shape

(2, 3)

In [0]:
linalg.svd(numSvdArr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [0]:
# Checkpoint # Finished till here?


In [0]:
# Scipy Statistics Module

from scipy.stats import norm
norm.rvs(loc=0, scale=1, size=10) # Pick random variables from the normal function

array([ 1.28590252,  2.01084374,  1.29577134, -0.15195433,  1.29827556,
        0.16298279, -0.71664032, -1.09819286, -0.65188358,  0.58739777])

In [0]:
norm.cdf(5, loc=1, scale=2)

0.9772498680518208